ent = input('Digite algo: ')
color = {'m': '\033[34;1m', 'l': '\033[m', 'v': '\033[32;1m'}
print(type(ent))
print(f'Está tudo em minúsculo? {color["m"]}{ent.islower()}{color["l"]}')
print(f'Está tudo em maiúsculo? {color["v"]}{ent.isupper()}{color["l"]}')
print(f'É alfanúmerico? {color["m"]}{ent.isalnum()}{color["l"]}')
print(f'É alfabético? {color["v"]}{ent.isalpha()}{color["l"]}')
print(f'É númerico? {color["m"]}{ent.isnumeric()}{color["l"]}')
print(f'É ASCII? {color["v"]}{ent.isascii()}{color["l"]}')
print(f'É decimal? {color["m"]}{ent.isdecimal()}{color["l"]}')
print(f'É um digito? {color["v"]}{ent.isdigit()}{color["l"]}')
print(f'É um identificador? {color["m"]}{ent.isidentifier()}{color["l"]}')
print(f'É possível mostrar todos os caracteres? {color["v"]}{ent.isprintable()}{color["l"]}')
print(f'Todas as palavras estão capitalizadas? {color["m"]}{ent.istitle()}{color["l"]}')
print(f'Todos os caracteres são espaços? {color["v"]}{ent.isspace()}{color["m"]}')
