ent = input('Digite algo: ')
print(type(ent))
print('Está tudo em minúsculo? ', ent.islower())
print('Está tudo em maiúsculo? ', ent.isupper())
print('É alfanúmerico? ', ent.isalnum())
print('É alfabético?', ent.isalpha())
print('É númerico? ', ent.isnumeric())
print('É ASCII? ', ent.isascii())
print('É decimal? ', ent.isdecimal())
print('É um digito? ', ent.isdigit())
print('É um identificador? ', ent.isidentifier())
print('É possível mostrar todos os caracteres? ', ent.isprintable())
print('Todas as palavras estão capitalizadas? ', ent.istitle())
print('Todos os caracteres são espaços?', ent.isspace())
