n = input('Digite seu nome completo: ').strip()
print(f'Seu nome em Maiúsculo é {n.upper()}')
print(f'Seu nome em Minúsculo é {n.lower()}')
print(f'Seu nome ao todo tem {len(n.replace(" ", ""))} letras')
# print(f'Seu nome ao todo tem {len(n) - n.count(" ")} letras')
print(f'Seu primero nome é {n.split()[0]} e ele tem {len(n.split()[0])} letras')
# print(f'Seu primero nome é {n.split()[0]} e ele tem {n.find(" ")} letras')
